### PR TITLE
Update for namespace changes

### PR DESCRIPTION
**Pull request by tybritten**
Closes https://github.com/ntt-sic/masakari-deploy/issues/1

### CODE REVIEW

**Comment by sampathP** [comment]
@vmtyler Thanks for the fix. 
Deployed without problem.
Though, have 2 comments. 
(1) Change the resource dpkg_package name from masakari_ to masakari-controller_ 
cookbooks/masakari_controller_conf/recipes/default.rb
(2) Rename the template files and change the source template names
- Rename the template files in cookbooks/masakari_compute_conf/templates/default/
       Ex: hostmonitor.conf.erb to masakari-hostmonitor.conf.erb
- Change the related source name of the template resources in /cookbooks/masakari_compute_conf/recipes/default.rb

**Comment by tybritten** [comment]
Will do

**Comment by tybritten** [comment]
Done

**Comment by sampathP** [comment]
@vmtyler thank you again.
 Looks good to me. +1

**Comment by toshikazu0314** [comment]
@vmtyler thanks for you pull request.
I checked and tested. It's okay. Let me merge.

**Pull request merged**
